version: '3.8'

services:
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Flask.Dockerfile
    image: flask-postgres
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  postgres_data:
